### ISSUE TITLE
Current tests failing on master

### ISSUE THREAD

**Issue by ardumont** [arkaline/lirecouleur#2]
A fresh clone of the repository, then triggering tests, there are currently
failures.

I had a look because i wanted to try and determine why it's slow to the point of hanging my
wife's libreoffice instance (her computer is a bit slow but still).

I wanted to dig in further but current tests are broken (and i don't understand
those yet).

Is this expected? Who is right, the tests or the code? Thanks for your time (i can switch to french if you prefer ;)

```
$ make -C make tests
cp ../src/opendocument-plugin/pythonpath/lirecouleur/lirecouleur.py ../tests/
cp ../src/opendocument-plugin/lirecouleur.dic ../tests/
python ../tests/tests_lirecouleur.py
F...FF.F.....F.......F.F..FFF
======================================================================
FAIL: test_mots (__main__.TestMotsRegleA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/tests_lirecouleur.py", line 107, in test_mots
    self.assert_mots_ok(mots)
  File "../tests/tests_lirecouleur.py", line 74, in assert_mots_ok
    self.assertEqual(actual_phonemes, expected_phonemes)
AssertionError: Lists differ: [('b', 'b'), ('a', 'a'), ('j_q_caduc', 'ye')] != [('b', 'b'), ('a', 'a'), ('j', 'y'), ('q_caduc', 'e')]

First differing element 2:
('j_q_caduc', 'ye')
('j', 'y')

Second list contains 1 additional elements.
First extra element 3:
('q_caduc', 'e')

- [('b', 'b'), ('a', 'a'), ('j_q_caduc', 'ye')]
?                             ^           -

+ [('b', 'b'), ('a', 'a'), ('j', 'y'), ('q_caduc', 'e')]
?                             ^^^^^^^^^^^


======================================================================
FAIL: test_mots (__main__.TestMotsRegleE)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/tests_lirecouleur.py", line 211, in test_mots
    self.assert_mots_ok(mots)
  File "../tests/tests_lirecouleur.py", line 74, in assert_mots_ok
    self.assertEqual(actual_phonemes, expected_phonemes)
AssertionError: Lists differ: [('a', 'a'), ('s', 'ss'), ('#', 'e'), ('w_a', 'oi'), ('r', 'r')] != [('a', 'a'), ('s', 'ss'), ('#', 'e'), ('wa', 'oi'), ('r', 'r')]

First differing element 3:
('w_a', 'oi')
('wa', 'oi')

- [('a', 'a'), ('s', 'ss'), ('#', 'e'), ('w_a', 'oi'), ('r', 'r')]
?                                          -

+ [('a', 'a'), ('s', 'ss'), ('#', 'e'), ('wa', 'oi'), ('r', 'r')]

======================================================================
FAIL: test_mots (__main__.TestMotsRegleG)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/tests_lirecouleur.py", line 236, in test_mots
    self.assert_mots_ok(mots)
  File "../tests/tests_lirecouleur.py", line 74, in assert_mots_ok
    self.assertEqual(actual_phonemes, expected_phonemes)
AssertionError: Lists differ: [('g', 'g'), ('a~', 'am'), ('m', 'm'), ('q_caduc', 'e')] != [('g', 'g'), ('a', 'a'), ('m', 'mm'), ('q_caduc', 'e')]

First differing element 1:
('a~', 'am')
('a', 'a')

- [('g', 'g'), ('a~', 'am'), ('m', 'm'), ('q_caduc', 'e')]
?                 -     -

+ [('g', 'g'), ('a', 'a'), ('m', 'mm'), ('q_caduc', 'e')]
?                                 +


======================================================================
FAIL: test_mots (__main__.TestMotsRegleI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/tests_lirecouleur.py", line 270, in test_mots
    self.assert_mots_ok(mots)
  File "../tests/tests_lirecouleur.py", line 74, in assert_mots_ok
    self.assertEqual(actual_phonemes, expected_phonemes)
AssertionError: Lists differ: [('f', 'f'), ('i', 'i'), ('j_q_caduc', 'lle')] != [('f', 'f'), ('i', 'i'), ('j', 'll'), ('q_caduc', 'e')]

First differing element 2:
('j_q_caduc', 'lle')
('j', 'll')

Second list contains 1 additional elements.
First extra element 3:
('q_caduc', 'e')

- [('f', 'f'), ('i', 'i'), ('j_q_caduc', 'lle')]
?                             ^           --

+ [('f', 'f'), ('i', 'i'), ('j', 'll'), ('q_caduc', 'e')]
?                             ^^^^^^^^^^^^


======================================================================
FAIL: test_mots (__main__.TestMotsRegleO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/tests_lirecouleur.py", line 339, in test_mots
    self.assert_mots_ok(mots)
  File "../tests/tests_lirecouleur.py", line 74, in assert_mots_ok
    self.assertEqual(actual_phonemes, expected_phonemes)
AssertionError: Lists differ: [('r', 'r'), ('w_a', 'oi')] != [('r', 'r'), ('wa', 'oi')]

First differing element 1:
('w_a', 'oi')
('wa', 'oi')

- [('r', 'r'), ('w_a', 'oi')]
?                 -

+ [('r', 'r'), ('wa', 'oi')]

======================================================================
FAIL: test_mots (__main__.TestMotsRegleW)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/tests_lirecouleur.py", line 458, in test_mots
    self.assert_mots_ok(mots)
  File "../tests/tests_lirecouleur.py", line 74, in assert_mots_ok
    self.assertEqual(actual_phonemes, expected_phonemes)
AssertionError: Lists differ: [('w_a', 'wa'), ('p', 'p'), ('i', 'i'), ('t', 't'), ('i', 'i')] != [('wa', 'wa'), ('p', 'p'), ('i', 'i'), ('t', 't'), ('i', 'i')]

First differing element 0:
('w_a', 'wa')
('wa', 'wa')

- [('w_a', 'wa'), ('p', 'p'), ('i', 'i'), ('t', 't'), ('i', 'i')]
?     -

+ [('wa', 'wa'), ('p', 'p'), ('i', 'i'), ('t', 't'), ('i', 'i')]

======================================================================
FAIL: test_mots (__main__.TestMotsRegleY)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/tests_lirecouleur.py", line 494, in test_mots
    self.assert_mots_ok(mots)
  File "../tests/tests_lirecouleur.py", line 74, in assert_mots_ok
    self.assertEqual(actual_phonemes, expected_phonemes)
AssertionError: Lists differ: [('v', 'v'), ('w_a', 'o'), ('j_a', 'ya'), ('z^_g', 'g'), ('q_caduc', 'e')] != [('v', 'v'), ('wa', 'o'), ('j_a', 'ya'), ('z^_g', 'g'), ('q_caduc', 'e')]

First differing element 1:
('w_a', 'o')
('wa', 'o')

- [('v', 'v'), ('w_a', 'o'), ('j_a', 'ya'), ('z^_g', 'g'), ('q_caduc', 'e')]
?                 -

+ [('v', 'v'), ('wa', 'o'), ('j_a', 'ya'), ('z^_g', 'g'), ('q_caduc', 'e')]

======================================================================
FAIL: test_sons_voyelles (__main__.TestSonsIsoles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/tests_lirecouleur.py", line 56, in test_sons_voyelles
    self.assertEqual(extraire_phonemes(son, son, 0), phonemes)
AssertionError: Lists differ: [('a', 'a'), ('m', 'm')] != [('a~', 'am')]

First differing element 0:
('a', 'a')
('a~', 'am')

First list contains 1 additional elements.
First extra element 1:
('m', 'm')

- [('a', 'a'), ('m', 'm')]
+ [('a~', 'am')]

======================================================================
FAIL: test_mots (__main__.TestSyllabesMots1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/tests_lirecouleur.py", line 649, in test_mots
    self.assert_syllabes_ok(mots)
  File "../tests/tests_lirecouleur.py", line 517, in assert_syllabes_ok
    (phoneme, u(grapheme)) for phoneme, grapheme in phonemes
AssertionError: Lists differ: [('m', 'm'), ('e^_comp', 'e'), ('j_x', 'illeu'), ('r', 'r')] != [('m', 'm'), ('e^_comp', 'e'), ('j', 'ill'), ('x', 'eu'), ('r', 'r')]

First differing element 2:
('j_x', 'illeu')
('j', 'ill')

Second list contains 1 additional elements.
First extra element 4:
('r', 'r')

- [('m', 'm'), ('e^_comp', 'e'), ('j_x', 'illeu'), ('r', 'r')]
?                                   --

+ [('m', 'm'), ('e^_comp', 'e'), ('j', 'ill'), ('x', 'eu'), ('r', 'r')]
?                                          +++++++++++


======================================================================
FAIL: test_mots (__main__.TestSyllabesMots2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/tests_lirecouleur.py", line 772, in test_mots
    self.assert_syllabes_ok(mots)
  File "../tests/tests_lirecouleur.py", line 517, in assert_syllabes_ok
    (phoneme, u(grapheme)) for phoneme, grapheme in phonemes
AssertionError: Lists differ: [('e^[18 chars]', 'g'), ('y', 'u'), ('i', 'i'), ('j_q_caduc', 'lle')] != [('e^[18 chars]', 'g'), ('y', 'u'), ('i', 'i'), ('j', 'll'), ('q_caduc', 'e')]

First differing element 4:
('j_q_caduc', 'lle')
('j', 'll')

Second list contains 1 additional elements.
First extra element 5:
('q_caduc', 'e')

- [('e^_comp', 'ai'), ('g', 'g'), ('y', 'u'), ('i', 'i'), ('j_q_caduc', 'lle')]
+ [('e^_comp', 'ai'),
+  ('g', 'g'),
+  ('y', 'u'),
+  ('i', 'i'),
+  ('j', 'll'),
+  ('q_caduc', 'e')]

----------------------------------------------------------------------
Ran 29 tests in 0.094s

FAILED (failures=10)
make: *** [Makefile:28: tests] Error 1
```

current system:
```
$ python3 --version
Python 3.7.6
$ uname -a
Linux yavin4 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
```

**Comment by arkaline** [comment]
The current repository is definitely outdated.
Please, contact me using http://lirecouleur.arkaline.fr/contact/

**Comment by ardumont** [comment]
I did not see the more up-to-date version [1]

¯\_(ツ)_/¯

That's great, heading there first (tasks i opened here may no longer be relevant ;)

[1] https://framagit.org/arkaline/lirecouleur

**Comment by arkaline** [comment]
Merci pour les remarques. Je vais intégrer dans le code dès que possible.
Pour éviter des dublons de code, le compte Github va être supprimé au profit du Gitlab mais il faut aussi que je rectifie quelques problèmes liés à la dernière mise à jour de ma machine pour le code soit à jour sur Gitlab... bref, je patauge.
